### ISSUE TITLE
Fuzzing: panicked at 'attempt to multiply with overflow'

### ISSUE THREAD

**Issue by PaulGrandperrin** [alexcrichton/rustc-demangle#9]
Hi,
I'm playing with libFuzzer and I found this bug:
```rust
demangle("_ZN2222222222222222222222EE"); // panicked at 'attempt to multiply with overflow'
```
I don't know the mangling format so I'm not even sure if this is a bug that makes sense and is worth fixing. 

<details>
<summary>backtrace</summary>

```
thread 'main' panicked at 'attempt to multiply with overflow', /home/paulg/.cargo/git/checkouts/rustc-demangle-919c95a986d4044e/48646c6/src/lib.rs:127:25
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:68
             at libstd/sys_common/backtrace.rs:57
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:380
   3: std::panicking::default_hook
             at libstd/panicking.rs:396
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:576
   5: std::panicking::begin_panic
             at libstd/panicking.rs:537
   6: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:521
   7: rust_begin_unwind
             at libstd/panicking.rs:497
   8: core::panicking::panic_fmt
             at libcore/panicking.rs:71
   9: core::panicking::panic
             at libcore/panicking.rs:51
  10: rustc_demangle::demangle
             at /home/paulg/.cargo/git/checkouts/rustc-demangle-919c95a986d4044e/48646c6/src/lib.rs:127
  11: playrust::main
             at src/main.rs:9
  12: std::rt::lang_start::{{closure}}
             at /checkout/src/libstd/rt.rs:74
  13: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:479
  14: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  15: std::rt::lang_start_internal
             at libstd/panicking.rs:458
             at libstd/panic.rs:365
             at libstd/rt.rs:58
  16: std::rt::lang_start
             at /checkout/src/libstd/rt.rs:74
  17: main
  18: __libc_start_main
  19: _start
```
</details>

**Comment by alexcrichton** [comment]
Awesome, thanks! I ended up running some more fuzzing and found a few more bugs!
